steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args:
    - c
    - git clone https://github.com/egnyte/gcr-cleaner.git
    - chmod +x gcr-cleaner.py
    - ./gcr-cleaner.py --days-to-keep $_DAYS_TO_KEEP --tags-to-keep $_TAGS_TO_KEEP --project $PROJECT_ID --do-it
